

-- Total de alumnos que han cursado UML en 2011 y 2012
SELECT 
COUNT(DISTINCT ALUMNO.RUN_ALUMNO) AS 'TOTAL DE ALUMNOS QUE HAN CURSADO UML EN 2011 Y 2012'
FROM ALUMNO
INNER JOIN NOTAS ON ALUMNO.RUN_ALUMNO = NOTAS.RUN_ALUMNO
INNER JOIN CURSO ON NOTAS.CODIGO_CURSO = CURSO.CODIGO_CURSO
INNER JOIN BIMESTRE ON NOTAS.ID_BIMESTRE = BIMESTRE.ID_BIMESTRE
WHERE CURSO.NOMBRE_CURSO = 'UML' AND (BIMESTRE.ANIO = 2011 OR BIMESTRE.ANIO = 2012);


--Profesores que dictaron UML el tercer bimestre de 2011
SELECT DISTINCT 
CONCAT(PROFESOR.RUN_PROFESOR, '-', PROFESOR.DV_PROFESOR) AS RUN_PROFESOR, 
(PROFESOR.NOMBRE + ' ' + PROFESOR.APELLIDO) AS NOMBRE_COMPLETO, 
CURSO.NOMBRE_CURSO, 
BIMESTRE.ANIO,
BIMESTRE.NUMERO_BIMESTRE
FROM PROFESOR
INNER JOIN ASIGNACION_CURSOS_PRO ON PROFESOR.RUN_PROFESOR = ASIGNACION_CURSOS_PRO.RUN_PROFESOR
INNER JOIN CURSO ON ASIGNACION_CURSOS_PRO.CODIGO_CURSO = CURSO.CODIGO_CURSO
INNER JOIN BIMESTRE ON ASIGNACION_CURSOS_PRO.ID_BIMESTRE = BIMESTRE.ID_BIMESTRE
WHERE CURSO.NOMBRE_CURSO = 'UML' AND BIMESTRE.ANIO = 2011 AND BIMESTRE.NUMERO_BIMESTRE = 3;


--Lista de cursos que ha aprobado el alumno Perez (bimestre, año, profesor y nota)
SELECT 
CURSO.*, 
BIMESTRE.ANIO, 
BIMESTRE.NUMERO_BIMESTRE, 
(PROFESOR.NOMBRE + ' '+ PROFESOR.APELLIDO) AS NOMBRE_COMPLETO_PROFESOR , 
(ALUMNO.NOMBRE + ' '+ ALUMNO.APELLIDO) AS NOMBRE_COMPLETO_ALUMNO , 
NOTAS.NOTA
FROM CURSO
INNER JOIN NOTAS ON CURSO.CODIGO_CURSO = NOTAS.CODIGO_CURSO
INNER JOIN BIMESTRE ON NOTAS.ID_BIMESTRE = BIMESTRE.ID_BIMESTRE
INNER JOIN ASIGNACION_CURSOS_PRO ON CURSO.CODIGO_CURSO = ASIGNACION_CURSOS_PRO.CODIGO_CURSO
INNER JOIN PROFESOR ON ASIGNACION_CURSOS_PRO.RUN_PROFESOR = PROFESOR.RUN_PROFESOR
INNER JOIN ALUMNO ON NOTAS.RUN_ALUMNO = ALUMNO.RUN_ALUMNO
WHERE ALUMNO.APELLIDO = 'PEREZ';


--Profesores que pueden dictar .NET
SELECT DISTINCT 
CONCAT(PROFESOR.RUN_PROFESOR, '-', PROFESOR.DV_PROFESOR) AS RUN_PROFESOR,
(PROFESOR.NOMBRE + ' ' + PROFESOR.APELLIDO) AS NOMBRE_COMPLETO
FROM PROFESOR
INNER JOIN ASIGNACION_CURSOS_PRO ON PROFESOR.RUN_PROFESOR = ASIGNACION_CURSOS_PRO.RUN_PROFESOR
INNER JOIN CURSO ON ASIGNACION_CURSOS_PRO.CODIGO_CURSO = CURSO.CODIGO_CURSO
WHERE CURSO.NOMBRE_CURSO = '.NET';



--Salas de clases disponibles en las que se pueda dictar EJB para el primer bimestre de 2014.
SELECT SALA.*
FROM SALA
LEFT JOIN ASIGNACION_CURSOS_ALU ON SALA.CODIGO_SALA = ASIGNACION_CURSOS_ALU.CODIGO_SALA
LEFT JOIN CURSO ON ASIGNACION_CURSOS_ALU.CODIGO_CURSO = CURSO.CODIGO_CURSO
LEFT JOIN BIMESTRE ON ASIGNACION_CURSOS_ALU.ID_BIMESTRE = BIMESTRE.ID_BIMESTRE
WHERE CURSO.NOMBRE_CURSO IS NULL OR (CURSO.NOMBRE_CURSO = 'EJB' AND BIMESTRE.ANIO = 2014 AND BIMESTRE.NUMERO_BIMESTRE = 1);


--Total de cursos dictados y alumnos atendidos por el profesor Perez en 2011 y 2012

SELECT 
    COUNT(DISTINCT ASIGNACION_CURSOS_PRO.ID_ASIGNACION) AS TOTAL_CURSOS,
    COUNT(DISTINCT NOTAS.RUN_ALUMNO) AS TOTAL_ALUMNOS
FROM ASIGNACION_CURSOS_PRO
INNER JOIN PROFESOR ON ASIGNACION_CURSOS_PRO.RUN_PROFESOR = PROFESOR.RUN_PROFESOR
INNER JOIN CURSO ON ASIGNACION_CURSOS_PRO.CODIGO_CURSO = CURSO.CODIGO_CURSO
INNER JOIN BIMESTRE ON ASIGNACION_CURSOS_PRO.ID_BIMESTRE = BIMESTRE.ID_BIMESTRE
LEFT JOIN NOTAS ON ASIGNACION_CURSOS_PRO.CODIGO_CURSO = NOTAS.CODIGO_CURSO
WHERE PROFESOR.APELLIDO = 'PEREZ' AND YEAR(BIMESTRE.FECHA_INICIO) IN (2011, 2012);